/**
 * Typed manifest of the studio photography. The design system references photos
 * by key so layouts stay intentional — the strongest images are reserved for the
 * most important placements, and every image carries real alt text.
 *
 * `tone: "cool"` marks the few frames whose palette fights the brand (teal/navy
 * accents) — used only in small/utility placements, never as heroes.
 */

export type RoomType =
  | "living"
  | "kitchen"
  | "bedroom"
  | "bathroom"
  | "entry"
  | "dining"
  | "office"
  | "lobby";

export type Orientation = "portrait" | "square" | "landscape";

export interface Photo {
  key: string;
  src: string;
  width: number;
  height: number;
  orientation: Orientation;
  room: RoomType;
  tone: "warm" | "neutral" | "cool";
  /** Editorial strength for placement decisions. */
  rank: 1 | 2 | 3;
  alt: string;
  /** Suggested object-position when cropped tall/wide. */
  focus?: string;
}

const P = "/photography";

export const photos = {
  brandHero: {
    key: "brandHero",
    src: "/brand/brand-hero-living-room.jpg",
    width: 1024,
    height: 1536,
    orientation: "portrait",
    room: "living",
    tone: "warm",
    rank: 1,
    alt: "Walnut-panelled living room with a linen sofa, sculptural nesting tables and a low pendant, styled for the Stilio identity.",
    focus: "center",
  },
  livingPenthouseWarm: {
    key: "livingPenthouseWarm",
    src: `${P}/living-room-penthouse-warm.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "living",
    tone: "warm",
    rank: 1,
    alt: "Warm penthouse living room with herringbone oak floors, a linear fireplace and a low sectional in oatmeal linen.",
  },
  livingMinimalBlackArt: {
    key: "livingMinimalBlackArt",
    src: `${P}/living-room-minimal-black-art.jpg`,
    width: 1024,
    height: 1024,
    orientation: "square",
    room: "living",
    tone: "neutral",
    rank: 1,
    alt: "Pared-back living room with a cream sofa, a single large black abstract canvas and a slim travertine coffee table.",
  },
  livingScandiCalm: {
    key: "livingScandiCalm",
    src: `${P}/living-room-scandi-calm.jpg`,
    width: 1536,
    height: 1024,
    orientation: "landscape",
    room: "living",
    tone: "neutral",
    rank: 2,
    alt: "Calm Scandinavian living room with a grey sofa, a round oak coffee table and a woven lounge chair by a bright window.",
  },
  livingWarmMinimal: {
    key: "livingWarmMinimal",
    src: `${P}/living-room-warm-minimal.jpg`,
    width: 720,
    height: 1280,
    orientation: "portrait",
    room: "living",
    tone: "warm",
    rank: 2,
    alt: "Double-height living room with a curved white sofa, a tan leather armchair and a tufted ottoman on pale oak.",
  },
  livingLoftSectional: {
    key: "livingLoftSectional",
    src: `${P}/living-room-loft-sectional.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "living",
    tone: "warm",
    rank: 2,
    alt: "Loft living room with a taupe sectional, walnut shelving and a black steel coffee table against tall industrial windows.",
  },
  livingBrightAiry: {
    key: "livingBrightAiry",
    src: `${P}/living-room-bright-airy.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "living",
    tone: "neutral",
    rank: 3,
    alt: "Bright, airy living room with two curved sofas facing a low marble table and a walnut media console.",
  },
  livingMarbleLounge: {
    key: "livingMarbleLounge",
    src: `${P}/living-room-marble-lounge.jpg`,
    width: 1600,
    height: 1600,
    orientation: "square",
    room: "living",
    tone: "neutral",
    rank: 3,
    alt: "Open lounge with polished marble floors, deep cream seating and a connected bar area.",
  },
  livingOpenplanFireplace: {
    key: "livingOpenplanFireplace",
    src: `${P}/living-room-openplan-fireplace.jpg`,
    width: 1600,
    height: 1600,
    orientation: "square",
    room: "living",
    tone: "warm",
    rank: 2,
    alt: "Open-plan living and dining space with a suspended fireplace, marble floors and a round coffee table.",
  },
  livingMediaWallCity: {
    key: "livingMediaWallCity",
    src: `${P}/living-room-media-wall-city.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "living",
    tone: "warm",
    rank: 3,
    alt: "City-view living room with a dark media wall, an espresso accent wall and a linen sofa on herringbone oak.",
  },
  kitchenWalnutBlackHood: {
    key: "kitchenWalnutBlackHood",
    src: `${P}/kitchen-walnut-black-hood.jpg`,
    width: 720,
    height: 1280,
    orientation: "portrait",
    room: "kitchen",
    tone: "warm",
    rank: 1,
    alt: "Walnut kitchen with a matte-black hood surround, a glass globe pendant and open shelving above a stone worktop.",
  },
  kitchenMarbleIsland: {
    key: "kitchenMarbleIsland",
    src: `${P}/kitchen-marble-island.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "kitchen",
    tone: "warm",
    rank: 2,
    alt: "Bright kitchen with warm oak cabinetry, a marble-topped island, a brass pendant and two upholstered stools.",
  },
  kitchenWaterfallIsland: {
    key: "kitchenWaterfallIsland",
    src: `${P}/kitchen-waterfall-island.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "kitchen",
    tone: "warm",
    rank: 2,
    alt: "Large kitchen with a marble waterfall island, mixed oak and pale cabinetry and a chrome globe pendant.",
  },
  kitchenSkylightHex: {
    key: "kitchenSkylightHex",
    src: `${P}/kitchen-skylight-hex-island.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "kitchen",
    tone: "neutral",
    rank: 3,
    alt: "Architectural kitchen lit by twin skylights, with taupe cabinetry and a faceted marble-topped island.",
  },
  bedroomCharcoalGoldBranch: {
    key: "bedroomCharcoalGoldBranch",
    src: `${P}/bedroom-charcoal-gold-branch.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "bedroom",
    tone: "warm",
    rank: 1,
    alt: "Bedroom with a charcoal panelled headboard wall, a gilt branch artwork, warm oak floors and an upholstered bench.",
  },
  bedroomWarmOak: {
    key: "bedroomWarmOak",
    src: `${P}/bedroom-warm-oak.jpg`,
    width: 1024,
    height: 1024,
    orientation: "square",
    room: "bedroom",
    tone: "warm",
    rank: 2,
    alt: "Warm bedroom with oak headboard panelling, a round mirror, a long low dresser and sheer curtains.",
  },
  bedroomCharcoalSputnik: {
    key: "bedroomCharcoalSputnik",
    src: `${P}/bedroom-charcoal-sputnik.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "bedroom",
    tone: "neutral",
    rank: 3,
    alt: "Bedroom with a charcoal accent wall, a tufted headboard, a sputnik chandelier and pale oak flooring.",
  },
  bathroomStoneTub: {
    key: "bathroomStoneTub",
    src: `${P}/bathroom-stone-freestanding-tub.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "bathroom",
    tone: "neutral",
    rank: 1,
    alt: "Stone bathroom with a freestanding oval tub, a floating basin and a full-height window onto bare trees.",
  },
  bathroomWoodVanity: {
    key: "bathroomWoodVanity",
    src: `${P}/bathroom-wood-vanity.jpg`,
    width: 720,
    height: 1280,
    orientation: "portrait",
    room: "bathroom",
    tone: "warm",
    rank: 2,
    alt: "Compact bathroom with a floating walnut vanity, a vessel basin, a walk-in shower and warm cove lighting.",
  },
  entryStoneStair: {
    key: "entryStoneStair",
    src: `${P}/entry-hall-stone-stair.jpg`,
    width: 1600,
    height: 1200,
    orientation: "landscape",
    room: "entry",
    tone: "neutral",
    rank: 1,
    alt: "Entrance hall with a cantilevered stone staircase, a planted light well and continuous recessed floor lighting.",
  },
  staircaseFloatingLed: {
    key: "staircaseFloatingLed",
    src: `${P}/staircase-floating-led.jpg`,
    width: 1600,
    height: 1600,
    orientation: "square",
    room: "entry",
    tone: "neutral",
    rank: 1,
    alt: "Sculptural floating staircase wrapped in vertical LED lines against a stone feature wall.",
  },
  entryBronzePortal: {
    key: "entryBronzePortal",
    src: `${P}/entry-hall-bronze-portal.jpg`,
    width: 1600,
    height: 1234,
    orientation: "landscape",
    room: "entry",
    tone: "warm",
    rank: 1,
    alt: "Grand entry with grey stone cladding, a full-height bronze pivot door and a backlit niche.",
  },
  entryGardenStair: {
    key: "entryGardenStair",
    src: `${P}/entry-hall-garden-stair.jpg`,
    width: 1600,
    height: 1234,
    orientation: "landscape",
    room: "entry",
    tone: "warm",
    rank: 2,
    alt: "Entry hall where afternoon light rakes across a stone staircase and an interior planting bed.",
  },
  diningClusterChandelier: {
    key: "diningClusterChandelier",
    src: `${P}/dining-room-cluster-chandelier.jpg`,
    width: 1600,
    height: 1600,
    orientation: "square",
    room: "dining",
    tone: "neutral",
    rank: 1,
    alt: "Formal dining room with eight upholstered chairs, a cascading crystal chandelier and a large dark canvas.",
  },
  lobbyMarbleFeature: {
    key: "lobbyMarbleFeature",
    src: `${P}/lobby-marble-feature-wall.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "lobby",
    tone: "cool",
    rank: 2,
    alt: "Reception lobby with a book-matched marble feature wall, walnut joinery and a ring chandelier.",
  },
  officeExecutive: {
    key: "officeExecutive",
    src: `${P}/office-executive-suite.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "office",
    tone: "warm",
    rank: 2,
    alt: "Executive office with warm timber-slat walls, a solid oak desk and framed abstract art.",
  },
  officeArchFeature: {
    key: "officeArchFeature",
    src: `${P}/office-arch-feature-wall.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "office",
    tone: "neutral",
    rank: 3,
    alt: "Workspace with an arched timber-slat feature niche, backlit shelving and a white workstation.",
  },
  officeMeetingWood: {
    key: "officeMeetingWood",
    src: `${P}/office-meeting-wood-ceiling.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "office",
    tone: "neutral",
    rank: 3,
    alt: "Meeting room with a timber-batten ceiling raft, an oak table and full-height glazed partitions.",
  },
  officeConference: {
    key: "officeConference",
    src: `${P}/office-conference-room.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "office",
    tone: "cool",
    rank: 3,
    alt: "Conference room with a charcoal feature wall, patterned carpet tile and a linear pendant over the table.",
  },
  officeNavyAccent: {
    key: "officeNavyAccent",
    src: `${P}/office-navy-accent.jpg`,
    width: 1280,
    height: 1280,
    orientation: "square",
    room: "office",
    tone: "cool",
    rank: 3,
    alt: "Private office with a deep navy niche, a chartreuse arc motif and paired oak desks.",
  },
} as const satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;
